<!-- Modal -->
<div class="modal fade bd-example-modal-xl" id="politicas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title font-weight-bold text-msa" id="exampleModalLongTitle">Politicas de privacidade</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p style="margin-top: 8.0pt; text-align: justify; line-height: 150%; text-autospace: none;"><span style="font-family: Arial;">Pol&iacute;tica de privacidade: A&nbsp;Me Salva A&iacute;.&nbsp;De CNPJ </span><span style="font-family: Arial;">30.423.752/0001-26</span><span style="font-family: Arial;">, localizada na </span><span style="font-family: Arial;">Rodovia BR 101, km 197 </span><span style="font-family: Arial;">Capoeiru&ccedil;u, Cachoiera/Ba, Edif&iacute;cio Sabi&aacute; N&ordm; 05 1&ordm; Andar Cep </span><span style="font-family: Arial;">44.300-000</span><span style="font-family: Arial;">, &ldquo;Me Salva A&iacute;&rdquo; &eacute; quem regula a pol&iacute;tica de privacidade dos servi&ccedil;os oferecidos sob a Plataforma Me Salva A&iacute;, definido abaixo.</span></p>
                <p style="margin-bottom: 3.75pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><strong><span style="font-family: Arial;">Pol&iacute;tica de privacidade para&nbsp;</span></strong><a href="http://politicaprivacidade.com/www.mesalvaai.com"><strong><span style="font-family: Arial; color: blue; border: none windowtext 1.0pt; padding: 0cm;">Me Salva A&iacute;</span></strong></a></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Todas as suas informa&ccedil;&otilde;es pessoais recolhidas, ser&atilde;o usadas para o ajudar a tornar a sua visita no nosso site o mais produtivo e agrad&aacute;vel poss&iacute;vel.</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">A garantia da confidencialidade dos dados pessoais dos utilizadores do nosso site &eacute; importante para o Me Salva A&iacute;.</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Todas as informa&ccedil;&otilde;es pessoais relativas a membros, assinantes, clientes ou visitantes que usem o Me Salva A&iacute; ser&atilde;o tratadas em concord&acirc;ncia com a Lei da Prote&ccedil;&atilde;o de Dados Pessoais de 26 de outubro de 1998 (Lei n.&ordm; 67/98).</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">A informa&ccedil;&atilde;o pessoal recolhida pode incluir o seu nome, e-mail, n&uacute;mero de telefone e/ou tele m&oacute;vel, morada, data de nascimento e/ou outros.</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">O uso do Me Salva A&iacute; pressup&otilde;e a aceita&ccedil;&atilde;o deste Acordo de privacidade. A equipa do Me Salva A&iacute; reserva-se ao direito de alterar este acordo sem aviso pr&eacute;vio. Deste modo, recomendamos que consulte a nossa pol&iacute;tica de privacidade com regularidade de forma a estar sempre atualizado.</span></p>
                <p style="text-align: justify; line-height: 150%; vertical-align: baseline; margin: 6.0pt 0cm .0001pt 0cm;"><strong><span style="font-family: Arial;">Os an&uacute;ncios</span></strong></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Tal como outros websites, coletamos e utilizamos informa&ccedil;&atilde;o contida nos an&uacute;ncios. A informa&ccedil;&atilde;o contida nos an&uacute;ncios, inclui o seu endere&ccedil;o IP (Internet Protocol), o seu ISP (Internet Service Provider, como o Sapo, Clix ou outro), o browser que utilizou ao visitar o nosso website (como o Internet Explorer ou o Firefox), o tempo da sua visita e que p&aacute;ginas visitou dentro do nosso website.</span></p>
                <p style="text-align: justify; line-height: 150%; vertical-align: baseline; margin: 6.0pt 0cm .0001pt 0cm;"><strong><span style="font-family: Arial;">Cookie DoubleClick Dart</span></strong></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">O Google, como fornecedor de terceiros, utiliza cookies para exibir an&uacute;ncios no nosso website;</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Com o cookie DART, o Google pode exibir an&uacute;ncios com base nas visitas que o leitor fez a outros websites na Internet;</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Os utilizadores podem desativar o cookie DART visitando a Pol&iacute;tica de&nbsp;</span><a href="http://politicaprivacidade.com/"><span style="font-family: Arial; color: windowtext; border: none windowtext 1.0pt; padding: 0cm; text-decoration: none; text-underline: none;">privacidade da rede de conte&uacute;do</span></a><span style="font-family: Arial; color: black;">&nbsp;e dos an&uacute;ncios do Google.</span></p>
                <p style="text-align: justify; line-height: 150%; vertical-align: baseline; margin: 6.0pt 0cm .0001pt 0cm;"><strong><span style="font-family: Arial;">Os Cookies e Web Beacons</span></strong></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Utilizamos cookies para armazenar informa&ccedil;&atilde;o, tais como as suas prefer&ecirc;ncias pessoas quando visita o nosso website. Isto poder&aacute; incluir um simples popup, ou uma liga&ccedil;&atilde;o em v&aacute;rios servi&ccedil;os que providenciamos, tais como f&oacute;runs.</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Em adi&ccedil;&atilde;o tamb&eacute;m utilizamos publicidade de terceiros no nosso website para suportar os custos de manuten&ccedil;&atilde;o. Alguns destes publicit&aacute;rios, poder&atilde;o utilizar tecnologias como os cookies e/ou web beacons quando publicitam no nosso website, o que far&aacute; com que esses publicit&aacute;rios (como o Google atrav&eacute;s do Google AdSense) tamb&eacute;m recebam a sua informa&ccedil;&atilde;o pessoal, como o endere&ccedil;o IP, o seu ISP, o seu browser, etc. Esta fun&ccedil;&atilde;o &eacute; geralmente utilizada para geotargeting (mostrar publicidade de Lisboa apenas aos leitores oriundos de Lisboa por ex.) ou apresentar publicidade direcionada a um tipo de utilizador (como mostrar publicidade de restaurante a um utilizador que visita sites de culin&aacute;ria regularmente, por ex.).</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">Voc&ecirc; det&eacute;m o poder de desligar os seus cookies, nas op&ccedil;&otilde;es do seu browser, ou efetuando altera&ccedil;&otilde;es nas ferramentas de programas Anti-Virus, como o Norton Internet Security. No entanto, isso poder&aacute; alterar a forma como interage com o nosso website, ou outros websites. Isso poder&aacute; afetar ou n&atilde;o permitir que fa&ccedil;a logins em programas, sites ou f&oacute;runs da nossa e de outras redes.</span></p>
                <p style="text-align: justify; line-height: 150%; vertical-align: baseline; margin: 6.0pt 0cm .0001pt 0cm;"><strong><span style="font-family: Arial;">Liga&ccedil;&otilde;es a Sites de terceiros</span></strong></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">O Me Salva A&iacute; possui liga&ccedil;&otilde;es para outros sites, os quais, a nosso ver, podem conter informa&ccedil;&otilde;es / ferramentas &uacute;teis para os nossos visitantes. A nossa pol&iacute;tica de privacidade n&atilde;o &eacute; aplicada a sites de terceiros, pelo que, caso visite outro site a partir do nosso dever&aacute; ler a pol&iacute;tica de privacidade do mesmo.</span></p>
                <p style="margin-bottom: .0001pt; text-align: justify; line-height: 150%; vertical-align: baseline;"><span style="font-family: Arial; color: black;">N&atilde;o nos responsabilizamos pela pol&iacute;tica de privacidade ou conte&uacute;do presente nesses mesmos sites.</span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>