<!-- Modal -->
<div class="modal fade bd-example-modal-xl" id="termos-de-uso" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title font-weight-bold text-msa" id="exampleModalLongTitle">Termos de uso</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p style="text-align: justify;">Pol&iacute;tica de privacidade: A&nbsp;Me Salva A&iacute;.&nbsp;De CNPJ 30.423.752/0001-26, localizada na Rodovia BR 101, km 197 Capoeiru&ccedil;u, Cachoiera/Ba, Edif&iacute;cio Sabi&aacute; N&ordm; 05 1&ordm; Andar Cep 44.300-000, &ldquo;Me Salva A&iacute;&rdquo; &eacute; quem regula a pol&iacute;tica de privacidade dos servi&ccedil;os oferecidos sob a Plataforma Me Salva A&iacute;.&nbsp;</p>
                <h2 style="text-align: left;">Termo de Compromisso do Contribu&iacute;dor</h2>
                <p style="text-align: justify;">Exp&otilde;e ao&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>, aqui considerado aquele devidamente autenticado no site&nbsp;<a href="http://www.mesalvaai.com.br">www.mesalvaai.com.br</a>, por este&nbsp;<strong>TERMO DE COMPROMISSO&nbsp;</strong>as condi&ccedil;&otilde;es de colabora&ccedil;&atilde;o de valores a determinada campanha.</p>
                <p style="text-align: justify;">O site&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>&nbsp;&eacute; um ambiente baseado na confian&ccedil;a, tanto pelos&nbsp;<strong>USU&Aacute;RIOS CRIADORES</strong>&nbsp;das campanhas quanto pelos&nbsp;<strong>USU&Aacute;RIOS CONTRIBUIDORES</strong>. Por isso, se n&atilde;o estiver de acordo com essas disposi&ccedil;&otilde;es, n&atilde;o prossiga com sua doa&ccedil;&atilde;o.</p>
                <ol style="text-align: justify;">
                <li>Este <strong>TERMO</strong> consolida a rela&ccedil;&atilde;o de doa&ccedil;&atilde;o mediante o&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>e a&nbsp;<strong>MSA</strong>, em complementa&ccedil;&atilde;o aos Termos de Uso do site&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, cujo conhecimento e concord&acirc;ncia pelo&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;s&atilde;o obrigat&oacute;rios, com as seguintes condi&ccedil;&otilde;es:</li>
                <li><strong><em> A MSA se compromete a:</em></strong></li>
                </ol>
                <p style="text-align: justify; padding-left: 40px;">2.1. Realizar a guarda dos valores a serem doados e, conforme o desfecho da campanha, repassar os valores para a Institui&ccedil;&atilde;o de ensino superior, de acordo com as caracter&iacute;sticas da campanha;</p>
                <p style="text-align: justify; padding-left: 40px;">2.2. Envidar seus esfor&ccedil;os de modo a permitir somente campanhas id&ocirc;neas e l&iacute;citas em seu ambiente. No entanto, pode existir campanhas com prop&oacute;sitos contr&aacute;rios ao site ou que contrariem os Termos de Uso, devendo os usu&aacute;rios da plataforma sempre ficarem atentos, pois &eacute; imposs&iacute;vel assegurar tal premissa de forma absoluta;</p>
                <p style="text-align: justify; padding-left: 40px;">2.3. Comunicar seus usu&aacute;rios caso haja alguma eventualidade no processamento ou envio de sua colabora&ccedil;&atilde;o;</p>
                <p style="text-align: justify; padding-left: 40px;">2.4. Fornecer os dados cadastrais dos&nbsp;<strong>USU&Aacute;RIOS CRIADORES</strong>&nbsp;aos&nbsp;<strong>USU&Aacute;RIOS CONTRIBUIDORES</strong>&nbsp;em caso de descumprimento de promessa de recompensa ou fato danoso que derem causa para que possam tomar as medidas legais cab&iacute;veis.</p>
                <ol style="text-align: justify;" start="3">
                <li><strong><em> O USU&Aacute;RIO CONTRIBUIDOR se compromete a:</em></strong></li>
                </ol>
                <p style="text-align: justify; padding-left: 40px;">3.1. Efetuar a doa&ccedil;&atilde;o &agrave; campanha que deseja contribuir e ficar atento &agrave; sua conclus&atilde;o com sucesso ap&oacute;s o per&iacute;odo de dura&ccedil;&atilde;o, para ter conhecimento da obriga&ccedil;&atilde;o da entrega de recompensa pelo&nbsp;<strong>USU&Aacute;RIO CRIADOR</strong>, se o caso;</p>
                <p style="text-align: justify; padding-left: 40px;">3.2. Ap&oacute;s confirmada a doa&ccedil;&atilde;o o&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;considerar&aacute; o ato como irretrat&aacute;vel, irrevog&aacute;vel, imodific&aacute;vel, aut&ecirc;ntico e leg&iacute;timo, devendo responder pelas perdas e danos causados por atos que provocar, a exemplo, mas n&atilde;o se restringindo, ao n&atilde;o reconhecimento da opera&ccedil;&atilde;o junto &agrave; institui&ccedil;&atilde;o financeira que controla seu cart&atilde;o de cr&eacute;dito;</p>
                <p style="text-align: justify; padding-left: 80px;">3.2.1. Como exce&ccedil;&atilde;o, poder&aacute; reclamar o&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;da sua doa&ccedil;&atilde;o e exigir o cancelamento caso descubra fato novo em rela&ccedil;&atilde;o ao ato da colabora&ccedil;&atilde;o que torne insustent&aacute;vel a confian&ccedil;a no&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;ou os motivos da campanha, justificando suas inten&ccedil;&otilde;es diretamente &agrave;&nbsp;<strong>MSA</strong>&nbsp;e arcando com eventuais tarifas e despesas devidas ao instituidor de pagamentos escolhido.</p>
                <p style="text-align: justify; padding-left: 40px;">3.3. Em casos de n&atilde;o cumprimento das obriga&ccedil;&otilde;es por parte do&nbsp;<strong>USU&Aacute;RIO CRIADOR</strong>, o&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;dever&aacute; proceder com sua execu&ccedil;&atilde;o for&ccedil;ada e, sob nenhuma hip&oacute;tese, revogar a doa&ccedil;&atilde;o aqui confirmada.</p>
                <ol style="text-align: justify;" start="4">
                <li><strong><em> A MSA n&atilde;o se responsabiliza:</em></strong></li>
                </ol>
                <p style="text-align: justify; padding-left: 40px;">4.1. Pelo inadimplemento das recompensas oferecidas pelos&nbsp;<strong>USU&Aacute;RIOS CRIADORES</strong>, tal qual o eventual insucesso do projeto descrito na campanha;</p>
                <p style="text-align: justify; padding-left: 40px;">4.2. Pela veracidade das informa&ccedil;&otilde;es veiculadas pelo&nbsp;<strong>USU&Aacute;RIO CRIADOR</strong>. Por isso, sempre utilize fontes adicionais de busca e pesquisa para ter certeza de sua idoneidade;</p>
                <p style="text-align: justify; padding-left: 40px;">4.3. Pelas frustra&ccedil;&otilde;es que o&nbsp;<strong>USU&Aacute;RIO CONTRIBUIDOR</strong>&nbsp;eventualmente sofrer em decorr&ecirc;ncia do desfecho da campanha que participar com a doa&ccedil;&atilde;o de valores. A&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o possui legitimidade para interferir ou controlar o que os&nbsp;<strong>USU&Aacute;RIOS CRIADORES </strong>executar&atilde;o.</p>
                <p style="text-align: justify; padding-left: 40px;">4.4. Pelos atos praticados pelo instituidor de pagamento escolhido, tal qual o valor das tarifas e descontos aplicados em virtude da cust&oacute;dia, armazenamento, retirada, convers&atilde;o do montante ou ato diverso que implique em pagamento pelo servi&ccedil;o contratado, nas formas da lei e dos Termos de Servi&ccedil;o do instituidor correspondente.</p>
                <ol style="text-align: justify;" start="5">
                <li>O presente <strong>TERMO DE COMPROMISSO</strong> &eacute; regido pelas leis da Rep&uacute;blica Federativa do Brasil e pelos Tratados e Conven&ccedil;&otilde;es Internacionais dos quais o Brasil &eacute; signat&aacute;rio, devendo ser interpretado no idioma portugu&ecirc;s, ficando eleito o F&oacute;rum da Comarca De Cachoeira do estado da Bahia, com expressa ren&uacute;ncia de qualquer outro, por mais privilegiado que seja ou venha a ser, para dirimir qualquer d&uacute;vida, pend&ecirc;ncia ou lit&iacute;gio oriundo deste contrato.</li>
                </ol>
                <p style="text-align: justify;">Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o</p>
                <p style="text-align: justify;">Bem-vindo ao Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>. A seguir apresentamos a voc&ecirc; (&ldquo;Visitante&rdquo;) os Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o (&ldquo;Termos&rdquo;), documento que relaciona as principais regras que devem ser observadas por todos que acessam o site&nbsp;<a href="http://www.mesalvaai.com.br">www.mesalvaai.com.br</a>,&nbsp;<a href="http://www.mesalvaai.com">www.mesalvaai.com</a>, seus subdom&iacute;nios ou utilizam suas ferramentas.</p>
                <p style="text-align: justify;">Ao visitar ou utilizar este site pressup&otilde;e-se a leitura e concord&acirc;ncia com todos os itens abaixo.</p>
                <p style="text-align: justify;">A&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>&nbsp;&eacute; um Portal que intermedia o levantamento de fundos (&ldquo;Contribui&ccedil;&otilde;es&rdquo;) para projetos e desenvolvimento de estudantes de forma colaborativa, comumente conhecido como crowdfunding, em ingl&ecirc;s.<br />Para os fins deste documento, devem se considerar as seguintes defini&ccedil;&otilde;es e descri&ccedil;&otilde;es para seu melhor entendimento:</p>
                <p style="text-align: justify;"><strong>Anti-Spam:</strong>&nbsp;Sistema que evita correspond&ecirc;ncias n&atilde;o desejadas, como publicidade em massa, pelo bloqueio de mensagens ou as movendo para pasta espec&iacute;fica.</p>
                <p style="text-align: justify;"><strong>Aplicativo Spider:</strong>&nbsp;Programa desenvolvido para obter informa&ccedil;&otilde;es de modo automatizado na internet, navegando pela web (teia) como se fosse uma spider (aranha).</p>
                <p style="text-align: justify;"><strong>Arranjadores de pagamento:</strong>&nbsp;Assim definidos por lei, prestadores de determinado servi&ccedil;o de pagamento ao p&uacute;blico aceito por mais de um recebedor, mediante acesso direto pelos usu&aacute;rios finais, pagadores e recebedores. Ex.: (Moip).</p>
                <p style="text-align: justify;"><strong>Campanha:</strong>&nbsp;Evento para arrecada&ccedil;&atilde;o de Contribui&ccedil;&otilde;es no Portal&nbsp;<strong><em>ME</em> <em>SALVA A&iacute;</em></strong>, com detalhes espec&iacute;ficos para a destina&ccedil;&atilde;o pretendida pelo seu Elaborador e por prazo determinado de dura&ccedil;&atilde;o, que pode ter, ou n&atilde;o, uma recompensa ao Colaborador.</p>
                <p style="text-align: justify;"><strong>Colaborador:</strong>&nbsp;Usu&aacute;rio cadastrado que envia Contribui&ccedil;&otilde;es &agrave; campanha, sob sua exclusiva responsabilidade.&nbsp;</p>
                <p style="text-align: justify;"><strong>Conta de Acesso:</strong>&nbsp;Credencial de um visitante cadastrado que permite o acesso &agrave; &aacute;rea restrita e &agrave;s funcionalidades exclusivas, que &eacute; definida pelo nome de usu&aacute;rio e senha.</p>
                <p style="text-align: justify;"><strong>Elaborador de Campanhas:&nbsp;</strong>Usu&aacute;rio cadastrado que desenvolve e apresenta uma Campanha, sob sua exclusiva responsabilidade, para capta&ccedil;&atilde;o de contribui&ccedil;&otilde;es para o desenvolvimento de seu projeto.</p>
                <p style="text-align: justify;"><strong>Layout:</strong>&nbsp;Conjunto compreendido entre apar&ecirc;ncia, design e fluxos do Portal.</p>
                <p style="text-align: justify;"><strong>Link:</strong>&nbsp;Terminologia para endere&ccedil;o de internet.</p>
                <p style="text-align: justify;"><strong>Logs:</strong>&nbsp;Registros de atividades do visitante efetuadas no Portal.</p>
                <p style="text-align: justify;"><strong>Portal <em>ME SALVA A&Iacute;:</em></strong>&nbsp;Designa o site de internet hospedado em&nbsp; <a href="http://www.mesalvaai.com">www.mesalvaai.com</a>&nbsp;e&nbsp;<a href="http://www.mesalvaai.com.br">www.mesalvaai.com.br</a>&nbsp;e seus subdom&iacute;nios.</p>
                <p style="text-align: justify;"><strong>Recompensas:</strong>&nbsp;Produtos ou servi&ccedil;os que ser&atilde;o oferecidos pelo usu&aacute;rio Elaborador de Campanhas aos usu&aacute;rios Colaboradores, sob sua exclusiva responsabilidade e sem rela&ccedil;&atilde;o com a&nbsp;<strong>MSA</strong>.</p>
                <p style="text-align: justify;"><strong>Site:</strong>&nbsp;Denomina&ccedil;&atilde;o para p&aacute;ginas de internet.</p>
                <p style="text-align: justify;"><strong>Visitante:</strong>&nbsp;Qualquer pessoa que navegar pelo Portal.</p>
                <p style="text-align: justify;"><strong>Usu&aacute;rio:</strong>&nbsp;Todo visitante cadastrado no Portal.</p>
                <p style="text-align: justify;"><strong>Webmastering:</strong>&nbsp;Compreende a cria&ccedil;&atilde;o, programa&ccedil;&atilde;o, desenvolvimento, controle e disponibilidade de p&aacute;ginas de internet.</p>
                <p style="text-align: justify;">&nbsp;</p>
                <p style="text-align: justify;"><strong>1 &ndash; Acesso e Restri&ccedil;&otilde;es de funcionalidade</strong></p>
                <p style="text-align: justify; padding-left: 40px;">1.1. Este Portal &eacute; dedicado &agrave; hospedagem do site de internet&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, cuja atividade &eacute; intermediar a arrecada&ccedil;&atilde;o de fundos para desenvolvimento de novos projetos, conhecido como crowdfunding.</p>
                <p style="text-align: justify; padding-left: 40px;">1.2. N&atilde;o &eacute; permitido aos visitantes e usu&aacute;rios acessarem as &aacute;reas de programa&ccedil;&atilde;o de Portal, seu banco de dados ou qualquer outro conjunto de informa&ccedil;&otilde;es que fa&ccedil;a parte da atividade de Webmastering, ficando sujeito quem o fizer &agrave; legisla&ccedil;&atilde;o penal brasileira e obrigados a reparar os danos que causarem.</p>
                <p style="text-align: justify; padding-left: 40px;">1.3. Tamb&eacute;m n&atilde;o &eacute; autorizado realizar ou permitir engenharia reversa, nem traduzir, decompilar, copiar, modificar, reproduzir, alugar, sublicenciar, publicar, divulgar, transmitir, emprestar, distribuir ou, de outra maneira, dispor das ferramentas de consulta deste Portal e de suas funcionalidades.</p>
                <p style="text-align: justify; padding-left: 40px;">1.4. Neste Portal &eacute; proibida a utiliza&ccedil;&atilde;o de aplicativos spider, ou de minera&ccedil;&atilde;o de dados, de qualquer tipo ou esp&eacute;cie, al&eacute;m de outro aqui n&atilde;o tipificado, mas que atue de modo automatizado, tanto para realizar opera&ccedil;&otilde;es massificadas ou para quaisquer outras finalidades, sob aplica&ccedil;&atilde;o da legisla&ccedil;&atilde;o penal brasileira e de reparar os danos que decorrerem desta utiliza&ccedil;&atilde;o.</p>
                <p style="text-align: justify; padding-left: 80px;">1.4.1. Este Portal foi desenvolvido para a utiliza&ccedil;&atilde;o por seres humanos da plataforma&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>&nbsp;com a finalidade de intermediar a arrecada&ccedil;&atilde;o de recursos pelos Elaboradores, com a finalidade de desenvolver novos projetos educacionais, de forma colaborativa, sendo proibidos quaisquer outros usos que n&atilde;o sejam estes.</p>
                <p style="text-align: justify; padding-left: 40px;">1.5. &Eacute; &ocirc;nus dos visitantes e usu&aacute;rios arcar com os meios necess&aacute;rios para navegar neste Portal, incluindo os requisitos para o acesso &agrave; Internet.</p>
                <p style="text-align: justify;"><strong>2 &ndash; Informa&ccedil;&otilde;es gerais sobre o site e seu funcionamento</strong></p>
                <p style="text-align: justify; padding-left: 40px;">2.1. Este Portal &eacute; apresentado ao p&uacute;blico da web na maneira como est&aacute; dispon&iacute;vel, podendo passar por constantes aprimoramentos e atualiza&ccedil;&otilde;es, n&atilde;o ficando obrigada a&nbsp;<strong>MSA</strong>&nbsp;a manter uma estrutura ou layout, se n&atilde;o por sua pr&oacute;pria conveni&ecirc;ncia.</p>
                <p style="text-align: justify; padding-left: 40px;">2.2. A&nbsp;<strong>MSA</strong>&nbsp;envida seus esfor&ccedil;os para a disponibilidade cont&iacute;nua e permanente do Portal, ficando o acesso sujeito, todavia, a eventos extraordin&aacute;rios, como desastres naturais, falhas ou colapsos nos sistemas centrais de comunica&ccedil;&atilde;o e acesso &agrave; internet ou fatos de terceiro, que fogem de sua esfera de vigil&acirc;ncia e responsabilidade.</p>
                <p style="text-align: justify; padding-left: 40px;">2.3. A&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o se responsabiliza por qualquer dano, preju&iacute;zo ou perda no equipamento dos visitantes e usu&aacute;rios causados por falhas no sistema, no servidor ou na conex&atilde;o &agrave; Internet, ainda que decorrentes de condutas de terceiros, inclusive por a&ccedil;&otilde;es de softwares maliciosos como v&iacute;rus, cavalos de tr&oacute;ia, e outros que possam, de algum modo, danificar o equipamento ou a conex&atilde;o dos visitantes e usu&aacute;rios em decorr&ecirc;ncia do acesso, utiliza&ccedil;&atilde;o ou navega&ccedil;&atilde;o neste Portal, bem como a transfer&ecirc;ncia de dados, arquivos, imagens, textos, &aacute;udios ou v&iacute;deos contidos no mesmo.</p>
                <p style="text-align: justify; padding-left: 40px;">2.4. Os visitantes e usu&aacute;rios n&atilde;o possuem qualquer direito para exigir a disponibilidade do Portal conforme melhor lhes convier, tampouco poder&atilde;o pleitear indeniza&ccedil;&atilde;o ou repara&ccedil;&atilde;o de danos em caso deste Portal permanecer fora do ar, independente da motiva&ccedil;&atilde;o.</p>
                <p style="text-align: justify; padding-left: 40px;">2.5. A&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o det&eacute;m qualquer responsabilidade pela navega&ccedil;&atilde;o dos visitantes e usu&aacute;rios nos links externos contidos no Portal, sendo o dever deles a leitura dos Termos de Uso e Pol&iacute;tica de Privacidade do site acessado e agir conforme o determinado. Tamb&eacute;m ser&atilde;o os principais respons&aacute;veis caso sobrevier algum dano ou preju&iacute;zo, uma vez que a navega&ccedil;&atilde;o segura cabe aos mesmos e que o Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>&nbsp;apenas apontou o link cabendo ao interessado a visita, ou n&atilde;o, ao site.</p>
                <p style="text-align: justify; padding-left: 80px;">2.5.1. A&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o verifica, controla, aprova ou garante a adequa&ccedil;&atilde;o ou exatid&atilde;o das informa&ccedil;&otilde;es ou dados disponibilizados em tais links, n&atilde;o sendo, portanto, respons&aacute;vel por preju&iacute;zos, perdas ou danos ocorridos pela visita de tais sites, cabendo ao usu&aacute;rio verificar a confiabilidade das informa&ccedil;&otilde;es e dados ali exibidos antes de utiliz&aacute;-los.</p>
                <p style="text-align: justify; padding-left: 80px;">2.5.2. Perdas, danos ou preju&iacute;zos ocasionados por atrasos, defeitos, erros ou omiss&otilde;es que possam existir nos sistemas ou servi&ccedil;os disponibilizados pelos sites referidos acima, n&atilde;o s&atilde;o de responsabilidade da&nbsp;<strong>MSA</strong>, mas sim de seu respectivo controlador.</p>
                <p style="text-align: justify; padding-left: 40px;">2.6. A <strong>MSA</strong>&nbsp;n&atilde;o se responsabiliza pelos atos praticados por visitantes e usu&aacute;rios em seu Portal, devendo cada um ser imputado de acordo com a qualidade do uso da plataforma.</p>
                <p style="text-align: justify;"><strong>3 &ndash; Comunica&ccedil;&atilde;o do Portal com seus visitantes e usu&aacute;rios</strong></p>
                <p style="text-align: justify; padding-left: 40px;">3.1. A&nbsp;<strong>MSA</strong>&nbsp;poder&aacute; utilizar todos os canais de comunica&ccedil;&atilde;o fornecidos e autorizados com seus visitantes e usu&aacute;rios, nas suas mais diversas modalidades, seja e-mail, liga&ccedil;&atilde;o telef&ocirc;nica ou envio por SMS, dentre outros.</p>
                <p style="text-align: justify; padding-left: 80px;">3.1.1. A responsabilidade pelo recebimento dos comunicados &eacute; exclusiva dos visitantes e usu&aacute;rios, por isso &eacute; indispens&aacute;vel que sempre forne&ccedil;am os dados corretos e precisos, al&eacute;m de os manterem atualizados.</p>
                <p style="text-align: justify; padding-left: 80px;">3.1.2. &Eacute; igualmente de suas al&ccedil;adas deixarem seus sistemas de anti-spam configurados de modo que n&atilde;o interfiram no recebimento dos comunicados e materiais do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, n&atilde;o sendo aceit&aacute;vel nenhuma escusa caso n&atilde;o tenha tido acesso a algum e-mail em virtude desse bloqueio ou filtro similar.</p>
                <p style="text-align: justify;"><strong>4 &ndash; Privacidade dos visitantes e usu&aacute;rios no Portal</strong></p>
                <p style="text-align: justify; padding-left: 40px;">4.1. O Portal possui documento pr&oacute;prio, denominado Pol&iacute;tica de Privacidade, que regula o tratamento dado &agrave;s informa&ccedil;&otilde;es de cadastro e demais informa&ccedil;&otilde;es e dados coletados.</p>
                <p style="text-align: justify; padding-left: 40px;">4.2. A Pol&iacute;tica de Privacidade &eacute; parte integrante e insepar&aacute;vel dos presentes Termos, e pode ser acessada no link encontrado em seu rodap&eacute;.</p>
                <p style="text-align: justify; padding-left: 40px;">4.3. Caso alguma disposi&ccedil;&atilde;o da Pol&iacute;tica de Privacidade conflitar com qualquer outra do presente documento, dever&aacute; prevalecer o descrito na norma mais espec&iacute;fica.</p>
                <p style="text-align: justify;"><strong>5 &ndash; Obriga&ccedil;&otilde;es do Portal</strong></p>
                <p style="text-align: justify; padding-left: 40px;">5.1. A&nbsp;<strong>MSA</strong>&nbsp;se obriga com os visitantes e usu&aacute;rios e seus usu&aacute;rios a:</p>
                <p style="text-align: justify; padding-left: 80px;">5.1.1. Manter o ambiente virtual seguro, tal qual suas opera&ccedil;&otilde;es de gerenciamento e dados registrados para tanto, salvo por ato destrutivo de terceiro que v&aacute; al&eacute;m dos esfor&ccedil;os empenhados e do estado atual da tecnologia, hip&oacute;tese que n&atilde;o se responsabilizar&aacute; por danos oriundos dessa pr&aacute;tica danosa.</p>
                <p style="text-align: justify; padding-left: 80px;">5.1.2. Preservar a funcionalidade do site, com links n&atilde;o quebrados, utilizando layout que respeita a usabilidade, seguran&ccedil;a e navegabilidade, facilitando a navega&ccedil;&atilde;o sempre que poss&iacute;vel e garantindo um ambiente confi&aacute;vel para processar suas opera&ccedil;&otilde;es.</p>
                <p style="text-align: justify; padding-left: 80px;">5.1.3. Exibir as funcionalidades de maneira clara, completa, precisa e suficiente de modo que exista a exata percep&ccedil;&atilde;o das opera&ccedil;&otilde;es realizadas.</p>
                <p style="text-align: justify; padding-left: 80px;">5.1.4. Garantir, por meio do estado da t&eacute;cnica dispon&iacute;vel, o sigilo e confidencialidade dos dados inseridos nas funcionalidades oferecidas em seu Portal, somente sendo acess&iacute;veis a quem o usu&aacute;rio declinar, al&eacute;m de si pr&oacute;prio.</p>
                <p style="text-align: justify;"><strong>6 &ndash; Obriga&ccedil;&otilde;es do visitante</strong></p>
                <p style="text-align: justify; padding-left: 40px;">6.1. Os visitantes e usu&aacute;rios se obrigam a realizar uma navega&ccedil;&atilde;o com retid&atilde;o &eacute;tica, sempre respeitando as condi&ccedil;&otilde;es que regem a utiliza&ccedil;&atilde;o do Portal, incluindo, mas n&atilde;o se limitando aos Termos.</p>
                <p style="text-align: justify; padding-left: 40px;">6.2. Ao fornecer dados e informa&ccedil;&otilde;es os visitantes e usu&aacute;rios se obrigam a faz&ecirc;-lo sempre com compromisso de veracidade e autenticidade, sob pena da aplica&ccedil;&atilde;o das penas da lei, de indenizar a quem causar dano e de ter a conta de acesso do presente Portal exclu&iacute;da.</p>
                <p style="text-align: justify; padding-left: 40px;">6.3. Na incid&ecirc;ncia de danos ao Portal ou a terceiros, o respons&aacute;vel se compromete a arcar com todas as obriga&ccedil;&otilde;es de indenizar o sujeito lesado, n&atilde;o devendo a&nbsp;<strong>MSA</strong>&nbsp;responder por tais preju&iacute;zos.</p>
                <p style="text-align: justify; padding-left: 40px;">6.4. Os visitantes e usu&aacute;rios devem utilizar os recursos do presente Portal para as finalidades que foi constitu&iacute;do, sob pena da aplica&ccedil;&atilde;o das penas da lei, de indenizarem a quem causarem dano e de terem a conta de acesso do presente Portal exclu&iacute;da.</p>
                <p style="text-align: justify; padding-left: 40px;">6.5. Tamb&eacute;m, visitantes e usu&aacute;rios devem manter o sigilo dos dados de sua conta de acesso, sua senha e demais dispositivos de autentica&ccedil;&atilde;o em rela&ccedil;&atilde;o a terceiros, n&atilde;o os divulgando ou compartilhando com quem quer que seja, sob pena da exclus&atilde;o da conta e de ter de ressarcir os danos que sobrevierem dessa divulga&ccedil;&atilde;o indevida.</p>
                <p style="text-align: justify; padding-left: 80px;">6.5.1. Caso o usu&aacute;rio suspeite que a confidencialidade de sua senha foi quebrada ou que houve o comprometimento de algum dispositivo de autentica&ccedil;&atilde;o, este dever&aacute; proceder sua troca ou atualiza&ccedil;&atilde;o o mais r&aacute;pido poss&iacute;vel. Se n&atilde;o conseguir acessar a Internet para obter suporte, dever&aacute; buscar atendimento dentre os canais dispon&iacute;veis.</p>
                <p style="text-align: justify;"><strong>7 - Direitos autorais e propriedade intelectual de Portal</strong></p>
                <p style="text-align: justify; padding-left: 40px;">7.1. O uso comercial da express&atilde;o&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>&nbsp;como marca, nome empresarial ou nome de dom&iacute;nio, al&eacute;m dos conte&uacute;dos das telas de Portal, assim como os programas, bancos de dados, redes e seus arquivos s&atilde;o de propriedade da&nbsp;<strong>MSA</strong>&nbsp;e est&atilde;o protegidos pelas leis e tratados internacionais de direito autoral, marcas, patentes, modelos e desenhos industriais.</p>
                <p style="text-align: justify; padding-left: 40px;">7.2. Ao acessar este Portal, os visitantes e usu&aacute;rios declaram que ir&atilde;o respeitar todos os direitos de propriedade intelectual e os decorrentes da prote&ccedil;&atilde;o de marcas, patentes e/ou desenhos industriais, depositados ou registrados em nome da&nbsp;<strong>MSA</strong>, bem como de todos os direitos referentes a terceiros que porventura estejam, ou estiveram, de alguma forma, dispon&iacute;veis no Portal. O simples acesso ao Portal n&atilde;o confere a este qualquer direito ao uso dos nomes, t&iacute;tulos, palavras, frases, marcas, patentes, obras liter&aacute;rias, art&iacute;sticas, l&iacute;tero-musicais, imagens, dados e informa&ccedil;&otilde;es, dentre outras, que nele estejam ou estiveram dispon&iacute;veis.</p>
                <p style="text-align: justify; padding-left: 40px;">7.3. A reprodu&ccedil;&atilde;o dos conte&uacute;dos descritos anteriormente est&aacute; proibida, salvo com pr&eacute;via autoriza&ccedil;&atilde;o por escrito da&nbsp;<strong>MSA</strong>&nbsp;ou caso se destinem ao uso exclusivamente pessoal e sem que em nenhuma circunst&acirc;ncia os visitantes e usu&aacute;rios adquiram qualquer direito sobre os mesmos.</p>
                <p style="text-align: justify; padding-left: 40px;">7.4. &Eacute; permitido fazer somente o arquivo tempor&aacute;rio deste Portal e de seu conte&uacute;do, sendo vedada sua utiliza&ccedil;&atilde;o para finalidades comerciais, publicit&aacute;rias ou qualquer outra que contrarie a realidade para o qual foi concebido, conforme definido neste documento. Restam igualmente proibidas a reprodu&ccedil;&atilde;o, distribui&ccedil;&atilde;o e divulga&ccedil;&atilde;o, total ou parcial, dos textos, figuras, gr&aacute;ficos que comp&otilde;em o presente Portal, sem pr&eacute;via e expressa autoriza&ccedil;&atilde;o da&nbsp;<strong>MSA</strong>, sendo permitida somente a impress&atilde;o de c&oacute;pias para uso e arquivo pessoal, sem que sejam separadas as partes que permitam dar o fiel e real entendimento de seu conte&uacute;do e objetivo.</p>
                <p style="text-align: justify; padding-left: 40px;">7.5. Os visitantes e usu&aacute;rios assumem toda e qualquer responsabilidade, de car&aacute;ter civil e/ou criminal, pela utiliza&ccedil;&atilde;o indevida das informa&ccedil;&otilde;es, textos, gr&aacute;ficos, marcas, obras, imagens, enfim, de todo e qualquer direito de propriedade intelectual ou industrial deste Portal.</p>
                <p style="text-align: justify; padding-left: 40px;">7.6. Qualquer outro tipo de utiliza&ccedil;&atilde;o de material autorizado, inclusive para fins editoriais, comerciais ou publicit&aacute;rios, s&oacute; poder&aacute; ser feito mediante pr&eacute;vio e expresso consentimento da&nbsp;<strong>MSA</strong>.&nbsp; Os visitantes e usu&aacute;rios est&atilde;o cientes, atrav&eacute;s deste item, que o uso comercial n&atilde;o autorizado poder&aacute; incorrer em infra&ccedil;&otilde;es c&iacute;veis e criminais, por estar infringindo a lei dos direitos autorais.</p>
                <p style="text-align: justify; padding-left: 40px;">7.7. Qualquer reutiliza&ccedil;&atilde;o do material autorizado dever&aacute; ser objeto de uma nova autoriza&ccedil;&atilde;o da&nbsp;<strong>MSA</strong>.</p>
                <p style="text-align: justify; padding-left: 40px;">7.8. A autoriza&ccedil;&atilde;o para utiliza&ccedil;&atilde;o do material solicitado n&atilde;o poder&aacute; ser transferida a terceiros, mesmo que vinculados ao sujeito autorizado por alguma raz&atilde;o.</p>
                <p style="text-align: justify; padding-left: 40px;">7.9. Qualquer utiliza&ccedil;&atilde;o n&atilde;o contemplada na mencionada autoriza&ccedil;&atilde;o ser&aacute; considerada como uma viola&ccedil;&atilde;o dos direitos de autor e sujeita &agrave;s san&ccedil;&otilde;es cab&iacute;veis na Lei 9.610, de 19 de fevereiro de 1998, que protege os direitos autorais no Brasil.</p>
                <p style="text-align: justify; padding-left: 40px;">7.10. A utiliza&ccedil;&atilde;o das funcionalidades oferecidas se dar&aacute; na forma de presta&ccedil;&atilde;o de servi&ccedil;o, n&atilde;o conferindo ao usu&aacute;rio nenhum direito sobre o software utilizado pela&nbsp;<strong>MSA</strong>&nbsp;ou de suas estruturas de inform&aacute;tica que sustentam as aplica&ccedil;&otilde;es de internet.</p>
                <p style="text-align: justify; padding-left: 40px;">7.11. A eventual retirada de qualquer conte&uacute;do ou funcionalidade deste Portal, em decorr&ecirc;ncia de alguma reclama&ccedil;&atilde;o, dever&aacute; ser sempre compreendida como uma demonstra&ccedil;&atilde;o de nossa inten&ccedil;&atilde;o de evitar dissabores e, jamais, como reconhecimento de culpa ou de qualquer infra&ccedil;&atilde;o pela&nbsp;<strong>MSA</strong>&nbsp;a direito de terceiro.&nbsp;</p>
                <p style="text-align: justify; padding-left: 40px;">7.12. Salvo disposi&ccedil;&atilde;o espec&iacute;fica em contrato existente entre os visitantes e usu&aacute;rios com a&nbsp;<strong>MSA</strong>, esses ret&ecirc;m os direitos autorais dos conte&uacute;dos que j&aacute; possu&iacute;rem quando os enviam ao Portal, tais como, mas n&atilde;o limitadamente, a coment&aacute;rios, v&iacute;deos, imagens, &aacute;udio e mensagens, contudo, concedem uma licen&ccedil;a irrevog&aacute;vel, perp&eacute;tua, mundial, irrestrita, isenta de royalties e n&atilde;o exclusiva de reprodu&ccedil;&atilde;o, adapta&ccedil;&atilde;o, modifica&ccedil;&atilde;o, tradu&ccedil;&atilde;o, publica&ccedil;&atilde;o, distribui&ccedil;&atilde;o ou exibi&ccedil;&atilde;o no pr&oacute;prio Portal, possibilitando a melhor utiliza&ccedil;&atilde;o da ferramenta, maior divulga&ccedil;&atilde;o de algum produto, servi&ccedil;o ou atividade ligada ao Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>.</p>
                <p style="text-align: justify; padding-left: 40px;">7.13. Caso o visitante ou usu&aacute;rio enviar sugest&otilde;es para a&nbsp;<strong>MSA</strong>&nbsp;por meio do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em> </strong>ou pelos canais divulgados que diga respeito a ideias para novos produtos&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, melhorias nos seus produtos j&aacute; existentes, campanhas publicit&aacute;rias ou qualquer outra a&ccedil;&atilde;o de marketing a ser realizada pela&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, elas deixar&atilde;o de pertencer ao patrim&ocirc;nio imaterial do visitante ou do usu&aacute;rio, ingressando no da&nbsp;<strong>MSA</strong>, nada podendo reclamar neste sentido, sobretudo recompensa pecuni&aacute;ria pelo que foi enviado ou revis&atilde;o nos modelos usados.</p>
                <p style="text-align: justify;"><strong>8 &ndash; Das funcionalidades do Portal <em>ME SALVA A&Iacute;</em></strong></p>
                <p style="text-align: justify; padding-left: 40px;">8.1. O Portal apresenta a seus visitantes e usu&aacute;rios uma plataforma que viabiliza aos Elaboradores a apresenta&ccedil;&atilde;o de suas Campanhas aos potenciais Colaboradores. Caso os Colaboradores se identifiquem com o projeto apresentado, ou com o produto oferecido, eles poder&atilde;o contribuir financeiramente, possibilitando que o Elaborador viabilize seu projeto. A Me Salva Ai &eacute; um mero intermedi&aacute;rio, atuando na apresenta&ccedil;&atilde;o da Campanha e recebendo os recursos dos Colaboradores, por conta e ordem dos Elaboradores, n&atilde;o tendo qualquer responsabilidade pela Campanha, produtos ou projetos apresentados pelos Elaboradores.</p>
                <p style="text-align: justify; padding-left: 80px;">8.1.1. Somente &eacute; permitido aos usu&aacute;rios maiores de 18 anos utilizarem a plataforma.</p>
                <p style="text-align: justify; padding-left: 80px;">8.1.2. Em caso de cadastro de pessoa jur&iacute;dica, dever&aacute; ser indicada pessoa f&iacute;sica respons&aacute;vel pela conta, que deve atender aos crit&eacute;rios de idade acima.</p>
                <p style="text-align: justify; padding-left: 80px;">8.1.3. Como a Me Salva A&iacute; &eacute; um mero intermedi&aacute;rio na arrecada&ccedil;&atilde;o dos recursos, esta n&atilde;o &eacute; respons&aacute;vel pelo sucesso da Campanha, pela veracidade das informa&ccedil;&otilde;es apresentadas pelos Elaboradores, tampouco garante a entrega das recompensas ou a viabilidade do projeto apresentado pelos Elaboradores.</p>
                <p style="text-align: justify; padding-left: 80px;">8.1.4. Se uma Campanha n&atilde;o for bem sucedida, ou, de alguma forma um usu&aacute;rio se viu frustrado em virtude de informa&ccedil;&atilde;o inver&iacute;dica de outro veiculada no Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, a&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o ser&aacute; respons&aacute;vel pelas frustra&ccedil;&otilde;es e dissabores decorrentes desses fatos, pois n&atilde;o atua de forma alguma no desenvolvimento da Campanha ou se responsabiliza pelas contribui&ccedil;&otilde;es dos Colaboradores, sendo meramente um intermedi&aacute;rio que apresenta as Campanhas e coleta as Contribui&ccedil;&otilde;es por conta e ordem do Elaborador.</p>
                <p style="text-align: justify; padding-left: 40px;">8.2. O Portal apenas intermedia as Contribui&ccedil;&otilde;es dos usu&aacute;rios Colaboradores, com a posterior disponibiliza&ccedil;&atilde;o dos valores para o usu&aacute;rio Elaborador uma vez atingida ou superada a meta estabelecida na Campanha.</p>
                <p style="text-align: justify; padding-left: 80px;">8.2.1. As contribui&ccedil;&otilde;es s&atilde;o enviadas a t&iacute;tulo de doa&ccedil;&atilde;o do Colaborador ao Elaborador. Quando houver indica&ccedil;&atilde;o de recompensa pelo Elaborador, este &eacute; o &uacute;nico respons&aacute;vel pela sua confec&ccedil;&atilde;o e entrega ao Colaborador. Caso o Elaborador n&atilde;o cumpra com os prazos prometidos ou com a entrega das recompensas, o Colaborador poder&aacute; se utilizar de todos os meios legais frente ao Elaborador para fazer valer seus direitos e ter suas pretens&otilde;es atingidas. A Me Salva A&iacute; n&atilde;o se responsabiliza pela entrega das recompensas, tampouco por quaisquer custos incorridos pelo Colaborador caso este pretenda se valer de meios legais para ter suas pretens&otilde;es atendidas junto ao Elaborador.</p>
                <p style="text-align: justify; padding-left: 80px;">8.2.2. As campanhas n&atilde;o poder&atilde;o beneficiar a terceiros que n&atilde;o o pr&oacute;prio elaborador, ficando a cargo deste repassar o que foi arrecadado ou o resultado da campanha. Caso o benefici&aacute;rio se recusar a receber o que foi oferecido, os colaboradores n&atilde;o ter&atilde;o qualquer direito sobre o que foi enviado &agrave;&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, permanecendo o elaborador como o leg&iacute;timo detentor.</p>
                <p style="text-align: justify; padding-left: 80px;">8.2.3. Em caso de descumprimento pelo Usu&aacute;rio Elaborador de quaisquer das disposi&ccedil;&otilde;es da campanha criada, a <strong>MSA</strong>&nbsp;n&atilde;o ser&aacute; respons&aacute;vel por realizar o que n&atilde;o foi cumprido, especialmente, mas n&atilde;o se limitando a entregar determinado produto ou realizar o servi&ccedil;o prometido. O Usu&aacute;rio Colaborador dever&aacute; buscar a satisfa&ccedil;&atilde;o do que foi dado em compromisso pelas vias legais, sem qualquer interfer&ecirc;ncia, responsabilidade ou intermedia&ccedil;&atilde;o da Me Salva A&iacute;.</p>
                <p style="text-align: justify; padding-left: 40px;">8.3. A&nbsp;<strong>MSA</strong>&nbsp;poder&aacute; alterar os crit&eacute;rios de elegibilidade a qualquer momento. Tamb&eacute;m, possui a faculdade de se recusar a conceder conta de acesso a qualquer pessoa ou entidade que tiver descumprido os Termos ou documento legal do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong> e teve sua conta de acesso exclu&iacute;da por esta raz&atilde;o.</p>
                <p style="text-align: justify; padding-left: 40px;">8.4. Ao contribu&iacute;rem com as campanhas existentes os usu&aacute;rios colaboradores n&atilde;o adquirem qualquer direito &agrave; propriedade intelectual dos conte&uacute;dos enviados pelos usu&aacute;rios elaboradores, tampouco do produto ou servi&ccedil;o que ser&aacute; produzido ou desenvolvido.</p>
                <p style="text-align: justify; padding-left: 40px;">8.5. O usu&aacute;rio est&aacute; ciente que dever&aacute; possuir cadastro em um dos arranjadores de pagamento que o&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong> aceita em sua plataforma. Assim, dever&aacute; ler atentamente aos Termos de Servi&ccedil;o respectivos para que eleja qual utilizar&aacute;.</p>
                <p style="text-align: justify; padding-left: 80px;">8.5.1. Tamb&eacute;m, est&aacute; de acordo que ao utilizar essas plataformas poder&aacute; haver aplica&ccedil;&atilde;o de tarifas sobre o montante arrecadado, cujo pagamento est&aacute; vinculado exclusivamente &agrave; movimenta&ccedil;&atilde;o de capital no arranjador escolhido.</p>
                <p style="text-align: justify; padding-left: 40px;">8.6. Se o usu&aacute;rio elaborador oferecer mais de uma esp&eacute;cie de recompensa, poder&aacute; o usu&aacute;rio colaborador escolher a que melhor lhe agrada no momento da contribui&ccedil;&atilde;o, desde que atenda ao valor m&iacute;nimo necess&aacute;rio.</p>
                <p style="text-align: justify; padding-left: 40px;">8.7. A&nbsp;<strong>MSA</strong>&nbsp;se reserva no direito de n&atilde;o publicar ou excluir campanhas e conte&uacute;dos enviados pelos usu&aacute;rios, a qualquer tempo, sem pr&eacute;vio aviso e nenhum direito a indeniza&ccedil;&atilde;o a quem quer que seja, que contiverem:</p>
                <ul>
                <li style="list-style-type: none;">
                <ul style="text-align: justify; list-style-type: disc;">
                <li>Racismo ou discrimina&ccedil;&atilde;o de qualquer natureza;</li>
                <li>Bullying, Stalking ou qualquer outra esp&eacute;cie de constrangimento ilegal ou ass&eacute;dio;</li>
                <li>Manifesta viola&ccedil;&atilde;o a direito autoral ou direito de imagem;</li>
                <li>Utiliza&ccedil;&atilde;o de marcas, s&iacute;mbolos, logotipos ou emblemas de terceiros;</li>
                <li>Instiga&ccedil;&atilde;o ou apologia &agrave; pr&aacute;tica de crimes, como tr&aacute;fico ou uso de entorpecentes, estupro, homic&iacute;dio, estelionato, dentre outros;</li>
                <li>Manifesta pr&aacute;tica de ato contr&aacute;rio &agrave; lei, &agrave; ordem p&uacute;blica ou aos bons costumes;</li>
                <li>Uso da viol&ecirc;ncia, dissemina&ccedil;&atilde;o de &oacute;dio ou qualquer outra forma de agress&atilde;o ao bem-estar f&iacute;sico de algu&eacute;m;</li>
                <li>Atividade comercial similar ao&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong> ou que utilize a plataforma para angariar recursos por publicidade de terceiros ao inv&eacute;s de praticar a intera&ccedil;&atilde;o regular do ambiente;</li>
                <li>Erros ou suspeita de equ&iacute;vocos.</li>
                </ul>
                </li>
                </ul>
                <p style="text-align: justify; padding-left: 40px;">8.8. Os visitantes poder&atilde;o se valer do canal de &lsquo;Fale Conosco&rsquo; toda vez que presenciarem ou verificarem conte&uacute;do impr&oacute;prio no site.</p>
                <p style="text-align: justify; padding-left: 80px;">8.8.1. A den&uacute;ncia ser&aacute; sigilosa e preservar&aacute; a identidade do visitante.</p>
                <p style="text-align: justify; padding-left: 40px;">8.9. Os conte&uacute;dos enviados pelos usu&aacute;rios e publicados no Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong> n&atilde;o dever&atilde;o ser interpretados como opini&atilde;o da&nbsp;<strong>MSA</strong>, tampouco declara&ccedil;&atilde;o de concord&acirc;ncia com o que foi publicado. Os usu&aacute;rios s&atilde;o inteiramente respons&aacute;veis pelos conte&uacute;dos que submeterem ao Portal.</p>
                <p style="text-align: justify; padding-left: 40px;">8.10. Os usu&aacute;rios autorizam a&nbsp;<strong>MSA</strong>&nbsp;a divulgar amplamente as campanhas em execu&ccedil;&atilde;o e aqueles que promoveram as colabora&ccedil;&otilde;es nos mais diversos meios de comunica&ccedil;&atilde;o e m&iacute;dias, de modo a estimular maior participa&ccedil;&atilde;o nas atividades por outras pessoas e aumentar a chance de sucesso da campanha, sem a exig&ecirc;ncia de remunera&ccedil;&atilde;o ou contrapresta&ccedil;&atilde;o qualquer resultante dessa dissemina&ccedil;&atilde;o.</p>
                <p style="text-align: justify;"><strong>9 &ndash; Das modalidades de Campanha e Pagamentos</strong></p>
                <p style="text-align: justify; padding-left: 40px;">9.1. &ldquo;Flex&iacute;vel&rdquo;: A campanha &ldquo;Flex&iacute;vel&rdquo; &eacute; definida por per&iacute;odo de 1 a 90 dias em que o usu&aacute;rio elaborador estabelece um valor m&iacute;nimo para arrecada&ccedil;&atilde;o e, caso n&atilde;o seja atingido ao seu t&eacute;rmino, aproveitar&aacute; dos valores que foram reunidos para sua campanha.</p>
                <p style="text-align: justify; padding-left: 80px;">9.1.1. Se a campanha atingir ou superar a meta estabelecida, o valor total arrecadado ser&aacute; transferido para a conta da Institui&ccedil;&atilde;o de ensino, exceto por 10%, valor devido &agrave;&nbsp;<strong>MSA</strong>&nbsp;pelos servi&ccedil;os do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong> que ser&atilde;o automaticamente retidos no momento do envio, al&eacute;m de eventuais tributos.</p>
                <p style="text-align: justify; padding-left: 40px;">9.2. &ldquo;Contribui&ccedil;&atilde;o Inicial&nbsp;<strong>MSA</strong>&rdquo;: A&nbsp;<strong>MSA</strong>&nbsp;por mera liberalidade, e por acreditar nas Campanhas criadas no Portal, se compromete a realizar a primeira contribui&ccedil;&atilde;o em toda nova Campanha lan&ccedil;ada no Portal no valor de R$10,00 (dez reais).</p>
                <p style="text-align: justify; padding-left: 80px;">9.2.1. Este valor ser&aacute; vis&iacute;vel desde o primeiro momento, por&eacute;m s&oacute; ter&aacute; seu pagamento efetivado se a Campanha receber outra (s) contribui&ccedil;&atilde;o (R$) que some (m) um m&iacute;nimo de R$500,00 (quinhentos reais). Desta forma, a Contribui&ccedil;&atilde;o Inicial&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o ser&aacute; efetivada e/ou devida caso o valor final das contribui&ccedil;&otilde;es adicionais n&atilde;o atinja o valor m&iacute;nimo mencionado. A Me Salva A&iacute; poder&aacute; optar por fazer contribui&ccedil;&otilde;es iniciais maiores e o pagamento efetivo destes valores estar&aacute; sempre condicionado a uma arrecada&ccedil;&atilde;o da campanha 50 vezes maior do que o pr&ecirc;mio concedido.</p>
                <p style="text-align: justify; padding-left: 40px;">9.3. A&nbsp;<strong>MSA</strong>&nbsp;se reserva no direito de apenas fazer constar a Campanha em sua lista de Campanhas dispon&iacute;vel para pesquisa e localiza&ccedil;&atilde;o na Plataforma ap&oacute;s a efetiva&ccedil;&atilde;o da segunda contribui&ccedil;&atilde;o recebida.</p>
                <p style="text-align: justify; padding-left: 40px;">9.4. Todas as transa&ccedil;&otilde;es e opera&ccedil;&otilde;es utilizar&atilde;o o Real Brasileiro como c&acirc;mbio (BRL). O usu&aacute;rio elaborador da campanha &eacute; o respons&aacute;vel pelo pagamento de todos os impostos e taxas de servi&ccedil;os relacionados ao uso do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>, podendo ser descontados automaticamente pela&nbsp;<strong>MSA</strong>, para evitar sonega&ccedil;&atilde;o fiscal.</p>
                <p style="text-align: justify; padding-left: 40px;">9.5. O usu&aacute;rio colaborador &eacute; o &uacute;nico respons&aacute;vel por acompanhar a evolu&ccedil;&atilde;o da campanha, atrav&eacute;s de informa&ccedil;&otilde;es fornecidas por seu elaborador e, subsidiariamente, por detalhes enviados pela&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>. Por isso, est&aacute; ciente que a&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o tem nenhuma obriga&ccedil;&atilde;o de enviar status sobre as campanhas.</p>
                <p style="text-align: justify; padding-left: 80px;">9.5.1. O <strong><em>ME SALVA A&Iacute;</em></strong> n&atilde;o medir&aacute; esfor&ccedil;os para manter o usu&aacute;rio colaborador atualizado sobre do sucesso ou insucesso da campanha apoiada por ele, o que n&atilde;o representar&aacute; qualquer responsabilidade por parte da&nbsp;<strong>MSA</strong>, com o que expressamente concorda seus usu&aacute;rios.</p>
                <p style="text-align: justify; padding-left: 40px;">9.6. Tamb&eacute;m, a&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o possui qualquer responsabilidade, direta ou indireta, sobre as informa&ccedil;&otilde;es fornecidas pelo elaborador das campanhas, seja ela em rela&ccedil;&atilde;o ao seu desenvolvimento, recompensas oferecidas, tempo de execu&ccedil;&atilde;o ou relacionada a qualquer outro tipo de detalhe.</p>
                <p style="text-align: justify; padding-left: 40px;">9.7. A&nbsp;<strong>MSA</strong>&nbsp;n&atilde;o oferece nenhuma garantia em rela&ccedil;&atilde;o &agrave;s contribui&ccedil;&otilde;es realizadas pelos arranjadores de pagamento e nem responde por falhas no cart&atilde;o de cr&eacute;dito ou transfer&ecirc;ncias banc&aacute;rias, j&aacute; que as plataformas de pagamentos s&atilde;o independentes do Portal&nbsp;<strong><em>ME SALVA A&Iacute;</em></strong>.</p>
                <p style="text-align: justify;"><strong>10 &ndash; Atendimento do Portal <em>ME SALVA A&Iacute;</em></strong></p>
                <p style="text-align: justify; padding-left: 40px;">10.1. Caso os haja alguma d&uacute;vida sobre as condi&ccedil;&otilde;es estabelecidas neste termo ou qualquer documento do website, por favor, envie um e-mail para <u>msa@mesalvaai.com.</u> Ser&aacute; um prazer ajudar a esclarecer qualquer de suas d&uacute;vidas.</p>
                <p style="text-align: justify;"><strong>11 &ndash; Modifica&ccedil;&otilde;es destes Termos e Condi&ccedil;&otilde;es</strong></p>
                <p style="text-align: justify; padding-left: 40px;">11.1. Os presentes Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o est&atilde;o sujeitos a constante melhoria e aprimoramento. Assim, a&nbsp;<strong>MSA</strong>&nbsp;se reserva o direito de modificar a qualquer momento, de forma unilateral, o presente documento e sua Pol&iacute;tica de Privacidade.</p>
                <p style="text-align: justify; padding-left: 40px;">11.2. Ao navegar por este Portal e utilizar suas funcionalidades, voc&ecirc; aceita guiar-se pelos Termos e Condi&ccedil;&otilde;es de Uso do Portal&nbsp;<strong>ME SALVA AI</strong>, e pela Pol&iacute;tica de Privacidade que se encontram vigentes na data e, portanto, deve verificar os mesmos cada vez que visitar este Portal.</p>
                <p style="text-align: justify;"><strong>12 &ndash; Disposi&ccedil;&otilde;es Gerais</strong></p>
                <p style="text-align: justify; padding-left: 40px;">12.1. A toler&acirc;ncia do eventual descumprimento de quaisquer das cl&aacute;usulas e condi&ccedil;&otilde;es do presente instrumento n&atilde;o constituir&aacute; nova&ccedil;&atilde;o das obriga&ccedil;&otilde;es aqui estipuladas e tampouco impedir&aacute; ou inibir&aacute; a exigibilidade das mesmas a qualquer tempo.</p>
                <p style="text-align: justify; padding-left: 40px;">12.2. Este Portal tem como base o hor&aacute;rio oficial de Bras&iacute;lia.</p>
                <p style="text-align: justify; padding-left: 40px;">12.3. Caso alguma disposi&ccedil;&atilde;o destes Termos de Uso seja considerada ileg&iacute;tima por autoridade da localidade que o visitante ou usu&aacute;rio acessa o Portal, ou mant&eacute;m v&iacute;nculo, as demais condi&ccedil;&otilde;es permanecer&atilde;o em pleno vigor e efeito at&eacute; segunda ordem.</p>
                <p style="text-align: justify;"><strong>13 &ndash; Lei aplic&aacute;vel e Jurisdi&ccedil;&atilde;o</strong></p>
                <p style="text-align: justify; padding-left: 40px;">13.1. Os Termos e Condi&ccedil;&otilde;es de Uso aqui descritos s&atilde;o interpretados segundo a legisla&ccedil;&atilde;o brasileira, no idioma portugu&ecirc;s, sendo eleito o F&oacute;rum da comarca de Cachoeira no Estado da Bahia para dirimir qualquer lit&iacute;gio, quest&atilde;o ou d&uacute;vida superveniente, com expressa ren&uacute;ncia de qualquer outro, por mais privilegiado que seja.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>